### ISSUE TITLE
Changelog with range don't works

### ISSUE THREAD

**Issue by villander** [lerna/lerna-changelog#129]
```
➜  web_app git:(DE-57/automate-changelog) ✗ lerna-changelog --from=v2.7.0 --to=v2.9.0
```

*OUTPUT*
```
Error: Command failed: git log --oneline --pretty=%h;%D;%s;%cd --date=short v2.7.0..v2.9.0
fatal: ambiguous argument 'v2.7.0..v2.9.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'


    at makeError (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/node_modules/execa/index.js:172:9)
    at Function.module.exports.sync (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/node_modules/execa/index.js:341:15)
    at Object.listCommits (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/lib/git.js:67:10)
    at Changelog.getListOfCommits (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/lib/changelog.js:142:20)
    at Changelog.<anonymous> (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/lib/changelog.js:86:40)
    at step (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/lib/changelog.js:32:23)
    at Object.next (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/lib/changelog.js:13:53)
    at /Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/lib/changelog.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/villander/.nvm/versions/node/v8.11.4/lib/node_modules/lerna-changelog/lib/changelog.js:3:12)
```

**Comment by villander** [comment]
@Turbo87 both tags alredy exist


![image](https://user-images.githubusercontent.com/10222774/51931660-91f85f00-23e4-11e9-8861-227ee3870bc0.png)

**Comment by Turbo87** [comment]
then I don't know what's wrong. this is working fine for me. what is the output of `git --version`?

**Comment by villander** [comment]
@Turbo87 
```
➜  web_app git:(DE-57/automate-changelog) git --version
git version 2.17.2 (Apple Git-113)
```

**Comment by villander** [comment]
@Turbo87 after run `git fetch --tags` it's works for me.

but I still have a issue, I want generate changelog to my first release v2.7.0, how do it?

**Comment by Turbo87** [comment]
> but I still have an issue, I want generate changelog to my first release v2.7.0

you can find the SHA1 of your first commit, and use that instead of a tag: e.g. `--from=a4b267c2f`

**Comment by villander** [comment]
thank you ; )
