### ISSUE TITLE
Error when running `lerna-changelog` in org's repo.

### ISSUE THREAD

**Issue by leohxj** [lerna/lerna-changelog#135]
I want to use lerna-changelog in one of a org's repo. Here is the repo: [mjolnirjs](https://github.com/mjolnirjs/mjolnir).

I have set `GITHUB_AUTH` env vars (with `admin:org, repo` scope) , but when i run `lerna-changlog`, it comes with some error, below is the error log:

```bash
yarn run v1.17.0
$ lerna-changelog
Error: Command failed: git describe --abbrev=0 --tags
fatal: No names found, cannot describe anything.


    at makeError (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/node_modules/execa/index
.js:172:9)
    at Function.module.exports.sync (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/node_
modules/execa/index.js:341:15)
    at Object.lastTag (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/lib/git.js:61:18)
    at Changelog.<anonymous> (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/lib/changelo
g.js:65:40)
    at step (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/lib/changelog.js:32:23)
    at Object.next (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/lib/changelog.js:13:53
)
    at /Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/lib/changelog.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/lib/changelog.js:3:12)
    at Changelog.createMarkdown (/Users/leohxj/workspace/github/mjolnir/node_modules/lerna-changelog/lib/chang
elog.js:58:16)
✨  Done in 0.73s.
```

In another project which is my private repo, `lerna-changelog` works well.So, I doubt there is anything wrong with org's repo?

**Comment by Turbo87** [comment]
it sounds like your project might not have any git tags yet. obviously that shouldn't crash the program though 😅

**Comment by leohxj** [comment]
Oh, yes. It crashed because my repo has no tags yet...

**Comment by leohxj** [comment]
I hope lerna-changelog can give this error more detail in cli.

**Comment by WasiqB** [comment]
I'm also getting same Error. Any assistance to fix this issue would be highly appreciated.

```bash
> yarn lerna-changelog
Error: Command failed with exit code 128: git describe --abbrev=0 --tags
fatal: No names found, cannot describe anything.
    at makeError (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/execa-npm-5.1.1-191347acf5-fba9022c8c.zip/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/execa-npm-5.1.1-191347acf5-fba9022c8c.zip/node_modules/execa/index.js:194:17)
    at Object.lastTag (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/git.js:31:18)
    at Changelog.<anonymous> (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:31:56)
    at Generator.next (<anonymous>)
    at /Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:4:12)
    at Changelog.createMarkdown (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:30:16)
    at Object.<anonymous> (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/cli.js:77:64)
```
