### ISSUE TITLE
Cannot read map of undefined when running lerna-changelog

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna-changelog#29]
Not sure what is is happening, but when I run lerna-changelog I get the below errors.
I'm on windows git-bash shell.

Regards
```
C:\Users\rdani\AppData\Roaming\npm\node_modules\lerna-changelog\cli.js:15
    throw (e);
    ^

TypeError: Cannot read property 'map' of undefined
    at C:\Users\rdani\AppData\Roaming\npm\node_modules\lerna-changelog\lib\Changelog.js:232:34
    at Array.forEach (native)
    at C:\Users\rdani\AppData\Roaming\npm\node_modules\lerna-changelog\lib\Changelog.js:231:14
    at Array.map (native)
    at Changelog.getCommitsByCategory (C:\Users\rdani\AppData\Roaming\npm\node_modules\lerna-changelog\lib\Changelog.js:228:48)
    at Changelog.createMarkdown (C:\Users\rdani\AppData\Roaming\npm\node_modules\lerna-changelog\lib\Changelog.js:63:36)
    at Object.<anonymous> (C:\Users\rdani\AppData\Roaming\npm\node_modules\lerna-changelog\cli.js:10:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by pigcan** [comment]
got the same error

**Comment by pigcan** [comment]
please check `lerna.json` first

```diff
+"changelog": {
+  "repo": "yourOrg/yourRepo",
+  "labels": {
+    "tag: bugfix": "Bug fix",
+    "tag: enhancement": "Enhancement"
+  },
+ "cacheDir": ".changelog"
}
```


then `yourOrg/yourRepo` should exist the labels you define in `lerna.json`

you can easily create a label by this address `https://github.com/orgName/repoName/labels`

**Comment by danielo515** [comment]
Right. Please consider handling the exception and providing a more friendly error.

Regards
