### ISSUE TITLE
Fails on Windows

### ISSUE THREAD

**Issue by billyzkid** [lerna/lerna-changelog#36]
I get the following error on Windows -- it is caused by using `--pretty='format:'` with single quotes in the command. It works if I change it to use escaped double quotes (`--pretty=\"format:\"`).

```
Error: Command failed: git show -m --name-only --pretty='format:' --first-parent a554e49
fatal: invalid --pretty format: 'format:'

    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at execSync (C:\Code\untitled\node_modules\lerna-changelog\lib\execSync.js:15:34)
    at Changelog.getListOfUniquePackages (C:\Code\untitled\node_modules\lerna-changelog\lib\Changelog.js:153:30)
    at C:\Code\untitled\node_modules\lerna-changelog\lib\Changelog.js:103:41
    at Array.reduce (native)
    at C:\Code\untitled\node_modules\lerna-changelog\lib\Changelog.js:101:51
    at Array.forEach (native)
    at C:\Code\untitled\node_modules\lerna-changelog\lib\Changelog.js:98:12
    at Array.forEach (native)
```

Also, this packages depends on curl executable which is not installed by default in Windows 10. Would be an improvement to eliminate that dependency (or at least call it out).

**Comment by Turbo87** [comment]
this should be fixed in the most recent release. please let me know if you still have issues with this on Windows!
