### ISSUE TITLE
Error `No names found, cannot describe anything` when trying to generate CHANGELOG before creating any tags for new project

### ISSUE THREAD

**Issue by WasiqB** [lerna/lerna-changelog#731]
For my new project [boyka-java](https://github.com/WasiqBhamla/boyka-java), I tried generating CHANGELOG for unreleased initial version, but got the following Error.

```bash
> yarn lerna-changelog
Error: Command failed with exit code 128: git describe --abbrev=0 --tags
fatal: No names found, cannot describe anything.
    at makeError (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/execa-npm-5.1.1-191347acf5-fba9022c8c.zip/node_modules/execa/lib/error.js:60:11)
    at Function.module.exports.sync (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/execa-npm-5.1.1-191347acf5-fba9022c8c.zip/node_modules/execa/index.js:194:17)
    at Object.lastTag (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/git.js:31:18)
    at Changelog.<anonymous> (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:31:56)
    at Generator.next (<anonymous>)
    at /Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:4:12)
    at Changelog.createMarkdown (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/changelog.js:30:16)
    at Object.<anonymous> (/Users/wasiqbhamla/Documents/my-git/boyka-java/.yarn/cache/lerna-changelog-npm-2.2.0-b91705158b-34c0afdf6f.zip/node_modules/lerna-changelog/lib/cli.js:77:64)
```

Following is the `lerna.json` content:

```json
{
  "version": "0.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "changelog": {
    "repo": "WasiqBhamla/boyka-java",
    "nextVersion": "1.0.0",
    "labels": {
      "tag: new feature": ":rocket: New Feature",
      "tag: breaking change": ":boom: Breaking Change",
      "tag: bug fix": ":bug: Bug Fix",
      "tag: polish": ":nail_care: Polish",
      "tag: documentation": ":memo: Documentation",
      "tag: internal": ":house: Internal",
      "tag: performance": ":running_woman: Performance"
    },
    "cacheDir": ".changelog"
  }
}
```

> All my PR's are marked properly with the labels mentioned in lerna config.

Let me know if I am doing something wrong.

**Comment by Turbo87** [comment]
lerna-changelog needs at least one existing tag to work properly. from the error message it sounds like you don't have any yet.

you can work around it by explicitly specifying `--from` when calling it and passing in the SHA1 of your initial commit. (e.g. `--from c0ffee123`)

**Comment by WasiqB** [comment]
Thanks for responding @Turbo87 . I created a tag `v0.0.0` with my initial commit and then it worked fine.
