### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Turbo87** [lerna/lerna-changelog#79]
```
TypeError: Cannot read property 'map' of undefined
    at _loop_1 (/Users/tbieniek/Code/glimmer.js/node_modules/lerna-changelog/lib/changelog.js:271:51)
    at Changelog.fillInCategories (/Users/tbieniek/Code/glimmer.js/node_modules/lerna-changelog/lib/changelog.js:279:13)
    at Changelog.<anonymous> (/Users/tbieniek/Code/glimmer.js/node_modules/lerna-changelog/lib/changelog.js:76:30)
    at step (/Users/tbieniek/Code/glimmer.js/node_modules/lerna-changelog/lib/changelog.js:32:23)
    at Object.next (/Users/tbieniek/Code/glimmer.js/node_modules/lerna-changelog/lib/changelog.js:13:53)
    at fulfilled (/Users/tbieniek/Code/glimmer.js/node_modules/lerna-changelog/lib/changelog.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

after running `yarn changelog --tag-from v0.4.0` in https://github.com/glimmerjs/glimmer.js

**Comment by evocateur** [comment]
Glimmer doesn't have a lerna.json or `changelog` field in package.json, how is `lerna-changelog` supposed to work there?

**Comment by Turbo87** [comment]
Sorry, forgot to mention https://github.com/glimmerjs/glimmer.js/pull/27
